# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Avada First app"
client_id = "c0e5502ad7b45c37c6673a398b31f280"
application_url = "https://intelligence-wholesale-infected-f.trycloudflare.com/auth/shopify"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://intelligence-wholesale-infected-f.trycloudflare.com/auth/shopify/callback",
  "https://intelligence-wholesale-infected-f.trycloudflare.com/authSa/shopify/callback",
  "https://intelligence-wholesale-infected-f.trycloudflare.com/auth/shopify/embed/callback",
  "https://localhost:3000/auth/shopify/callback",
  "https://localhost:3000/authSa/shopify/callback",
  "https://localhost:3000/auth/shopify/embed/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-8145fb28.myshopify.com"
